name: CMake

on: [push, pull_request, workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_windows:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v1
        with:
          path: 'source'
          submodules: 'recursive'
          persist-credentials: false

      - name: configure
        run: mkdir build && cd build && cmake -DWORKFLOW=TRUE ..
      - name: build
        run: cd build && cmake --build . --target RecordingPlugin
      - name: build_test
        run: cd build && cmake --build . --target tests && cd Debug && ls && ./tests.exe
      #- name: android_build
      #  shell: cmd
      #  run: .\buildAndroid.bat